GET http://localhost:5000/api/admin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDkzNzc1MTMsIm5iZiI6MTU0OTM3NzUxMywianRpIjoiNDViOTkwYzUtZTgzYy00MTJhLWFlMDQtM2UwYTU4ZmRiMjVlIiwiZXhwIjoxNTQ5Mzc4NDEzLCJpZGVudGl0eSI6IjIyZmI3ZDhkLWRiOTMtNDExNS04MmM4LTE0MjZhMjZlZDI0NSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.8mhVdcAFv3E22DZCcygv3VSuZ_MCP-nvUzEUTIv8b14

###