POST http://localhost:5000/api/admin/code
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDkzNzkzNTcsIm5iZiI6MTU0OTM3OTM1NywianRpIjoiNjE3ODVmMDEtNjE1NS00NzcyLWFiOWYtZjc3ODE5MmNmMTg5IiwiZXhwIjoxNTQ5MzgwMjU3LCJpZGVudGl0eSI6IjY2ZDYxNWM2LTExZWUtNGM2MS05ODQ4LTM1Y2QzNzlkNGNkMSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.XQDGXltHdM4AaTzpSmr55aby7Fc7lXEtD6V__RgxrIg
Content-Type: application/json

{
  "class_name": "국어",
  "start": "2019-1-1 12:00:00",
  "end": "2019-1-1 13:00:00"
}

###