GET http://localhost:5000/api/admin/attendance/29494dd5-cb1b-441f-852a-236ae84470be
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDkzNzk4ODEsIm5iZiI6MTU0OTM3OTg4MSwianRpIjoiMGFkOTFhZWUtZjQ0Yy00MzBhLWEzZjAtZWYwYzRjZjQ3NmRjIiwiZXhwIjoxNTQ5MzgwNzgxLCJpZGVudGl0eSI6IjczYmI4YTliLTkwZWYtNDA0Ni1iMDNiLTI5OWQzZGIxZTY5ZCIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.S6ExCfu_53YNOJrdOPflcX6ZcWDRbxu36U1GqaO2mGs

###