GET http://localhost:5000/api/admin/attendance/29494dd5-cb1b-441f-852a-236ae84470be
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDkzNzk0NTMsIm5iZiI6MTU0OTM3OTQ1MywianRpIjoiOTlhMzcxOGItZjM1NC00YjUxLTk4NDEtODY5ZWRiOWVmNWYwIiwiZXhwIjoxNTQ5MzgwMzUzLCJpZGVudGl0eSI6IjM2ZWYwOTY1LTYxNGMtNDA5My1hMjdkLTdmOWQ0NWU4NDc0MSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.goDxwv6-Pk9h6S0FiD192vnMLjtC9jdLo3h-OQQpkD8

###