POST http://localhost:5000/api/users
Content-Type: application/json

{
  "username": "test",
  "password": "test1234",
  "name": "황선우",
  "studentId": "10101",
  "birth": "2019-02-05 12:45:39.517791",
  "profileImage": "aaa"
}

###