GET http://localhost:5000/api/student
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDkzNzU5MjAsIm5iZiI6MTU0OTM3NTkyMCwianRpIjoiZjRjM2RmYzItYTFiMi00MDE3LTk4N2YtM2VkMWFlYjQxNGZiIiwiZXhwIjoxNTQ5Mzc2ODIwLCJpZGVudGl0eSI6IjQ4NDBmYzQ5LTE1NGUtNDAzZi05ZWZhLTVlYTUyYWFlM2Y4MCIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.mOzR5RI78Mnmld1ilZ_H7xDI7TwyOqswhdQrSzjcyME

###