GET http://localhost:5000/api/student
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDkzNzYzMDIsIm5iZiI6MTU0OTM3NjMwMiwianRpIjoiODUxZmQwMTUtNTM2YS00OTdjLWJhZmItYjg3ZDFlM2RhZTQ1IiwiZXhwIjoxNTQ5Mzc3MjAyLCJpZGVudGl0eSI6Ijk5MDZmZWFjLWI5MjMtNDg3OS1hZDIxLWUwYTk0YzcyNWRhYiIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.FoQWRX6EBg6AVfsvLJtbhOMhW4THPclOqUQBSAZ-StI

###