GET http://localhost:5000/api/student/auth/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDkzNzU2NTUsIm5iZiI6MTU0OTM3NTY1NSwianRpIjoiNzkwNTAxMTItM2M2ZC00MDViLTg5Y2EtMmNhYWM2YmEwODhmIiwiZXhwIjoxNTUxOTY3NjU1LCJpZGVudGl0eSI6IjJhYzM4NDYxLWNiYjItNDc2OS1hMGM3LTNhNTgxMzYyYjE1OSIsInR5cGUiOiJyZWZyZXNoIn0.skXwm4IT0zYoTy7J1kSAbMeBMc9CvjXt1lCobArH-Jw

###