POST http://localhost:5000/api/student/attendance/29494dd5-cb1b-441f-852a-236ae84470be
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDkzNzk5NjUsIm5iZiI6MTU0OTM3OTk2NSwianRpIjoiNzA2NGNhMjEtMzhiMS00ODIzLWEwODYtNGQ3YzExZjYxYzMyIiwiZXhwIjoxNTQ5MzgwODY1LCJpZGVudGl0eSI6IjQwYjM3ZWQwLTg4ZTUtNDZkOS1iMTFmLTc0MzNkNjA5NzU4OSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dtqG1qtJrbAO_vzapkTZa95j2o99SPD860Cx4D9BqSE

###